name: Jutuskeem
version: ${project.version}
author: mikroskeem
main: eu.mikroskeem.jutuskeem.Main
description: Extremely simple chat plugin
webpage: https://mikroskeem.eu
softdepend:
- Vault

commands:
  jutuskeem:
    permission: jutuskeem.use

  nickname:
    permission: jutuskeem.nickname
    aliases: [nick, clearnickname, clearnick]

  tell:
    permission: jutuskeem.tell
    aliases: [msg, reply, t, m, r]

  socialspy:
    permission: jutuskeem.socialspy
    aliases: [ss]

#  ignore:
#    permission: jutuskeem.ignore

permissions:
  jutuskeem.use:
    description: Reload plugin configuration
    default: op

  jutuskeem.chatcolors:
    description: Allows to use colors/formatting in chat
    default: op

  jutuskeem.nickname:
    description: Allows to manage your nickname
    default: op

  jutuskeem.nickname.clearothers:
    description: Allows to clear other players nicknames
    default: op

  jutuskeem.tell:
    description: Allows to send private messages to players
    default: true

  jutuskeem.socialspy:
    description: Allows to see other players private messages
    default: op

#  jutuskeem.ignore:
#    description: Allows to ignore other players
#    default: true
#
#  jutuskeem.ignore.exempt:
#    description: Allows ignoring players to see ignored player messages despite their setting
#    default: op
#
#  jutuskeem.allowglobal:
#    description: Allows talking globally over worlds (toggleable)
#    default: op